### ISSUE TITLE
Support for BEP-5: DHT Protocol

### ISSUE THREAD

**Issue by karuppiah7890** [atomashpolskiy/bt#2]
I am a newbie coder. I was planning to implement BitTorrent protocol. It's like some magic for me. But I decided to checkout libraries first, and many of the libraries said in docs that they don't have DHT support and ones which did were messy. 

But to check out the performance, I am gonna try out all of them, of course including bt. I was just wondering if you have plans to implement the BPE-5, the DHT, so that I can use it in the future. Or, if I have some confidence, I think I will look into your code and think about implementing DHT and contributing to bt, though it's not an easy task for a developer like me..

**Comment by atomashpolskiy** [comment]
Hi @karuppiah7890 ! Thanks for your interest, it's really important for me that people are getting interested in Bt.

It's absolutely a number one feature that I'm planning to include in Bt. I've done a bit of a research some time ago, and it turned out that there are just a few Mainline DHT implementations in Java, and frankly neither of those seems to be user-friendly/straight-forward to use, esp. as an embedded library.

That said, I think that the DHT support fits somewhat better into a 1.x release, rather than the initial one. I'm mostly done with preparing the initial release, so the API should be more or less stable from now on (excluding the bt-tests module, I'm going to refactor it in the nearest time). You can give it a try if you want, and feel free to ping me if you have any questions/suggestions.

Regarding your thoughts on the performance comparison of open-source BitTorrent libraries -- I think it's an absolutely terrific idea! In fact I've been doing simple comparisons between Bt and [TTorrent](https://github.com/mpetazzoni/ttorrent), and it seems that Bt is doing quite good in terms of efficiency/performance, and completely blows TTorrent out of the water in RAM usage. So I personally (and a lot of folks I suppose) would be highly interested in seeing some articles/blog posts on this topic.

**Comment by karuppiah7890** [comment]
I think it makes sense. TTorrent is famous and I just tried it. and It's not even working, I don't know how to get it work. Bad Examples. And no API Docs. 

When will Bt docs be available ?

**Comment by atomashpolskiy** [comment]
Latest JavaDoc is built automatically for every new commit to master. Please see http://atomashpolskiy.github.io/bt/javadoc/latest/
CLI client is also a good place to start from (shows the most basic usage example): https://github.com/atomashpolskiy/bt/blob/master/bt-cli/src/main/java/bt/cli/CliClient.java

I'm also planning to provide more formal documentation with the 1.0 release, which will hopefully be before the New Year.

**Comment by karuppiah7890** [comment]
Nice. Checking on it

And do provide this link in the website, I don't think I saw any direct link. And do provide it in README too, for now

**Comment by the8472** [comment]
> I've done a bit of a research some time ago, and it turned out that there are just a few Mainline DHT implementations in Java, and frankly neither of those seems to be user-friendly/straight-forward to use, esp. as an embedded library.

I am the author of [mldht](https://github.com/the8472/mldht). It's intended to be used as a library, but I don't have many downstream consumers so it's mostly run in a few specialized stand-alone uses which I manage myself.

If you have any feedback what makes it difficult to use I might be able to address those issues.

**Comment by atomashpolskiy** [comment]
@the8472 , thanks for showing up! Yeah, I've considered using your implementation, but it's not published in Maven Central. Also I recall that in order to build it locally I had to manually add *eddsa* library and remove `the8472.test.Bep44` class due to compilation errors. If you could release a stable version, I'd be happy to take another look and experiment with using it!

**Comment by atomashpolskiy** [comment]
@the8472 , I just took another look at mldht and finally remembered what my main issue with it was. It's GPL license, which is incompatible with Apache that is used by Bt. May I ask you why have you decided to go with a copyleft license?

**Comment by the8472** [comment]
That was the license the original maintainer chose before I took it over many years ago. Some of the commit history was lost so I'm not sure how many LoC authored by him remain. But I can ask him if he would let me relicense it.

**Comment by the8472** [comment]
>  I had to manually add eddsa library and remove the8472.test.Bep44 class due to compilation errors. 

That shouldn't be necessary. Travis compiles it just fine. Maybe you forgot to do a recursive clone or the build-helper-maven-plugin was not applied properly?

Currently the patched version of ed25519 is necessary until https://github.com/str4d/ed25519-java/issues/17 makes it into a release. BEP44 key handling is specifies the key format in a way that is not covered by the previously available constructors.

**Comment by atomashpolskiy** [comment]
This was indeed my fault. Hadn't seen git submodules until this day. `git clone --recursive` did the trick, now the project builds just fine. Thanks!

> That was the license the original maintainer chose before I took it over many years ago. ... But I can ask him if he would let me relicense it.

This would be incredibly nice of you!

**Comment by str4d** [comment]
I should be making a new release that includes str4d/ed25519-java#17 shortly 😃

**Comment by atomashpolskiy** [comment]
Hey @str4d , cool! A quite remarkable release train it is going to be :)

**Comment by str4d** [comment]
New release should be dropping this weekend.

**Comment by the8472** [comment]
Btw, you can include it as maven dep it via [jitpack](https://jitpack.io/#the8472/mldht/0.1.0)

**Comment by karuppiah7890** [comment]
Wow, nice to see Bt rising up with cool features :)

**Comment by atomashpolskiy** [comment]
Thanks mate ;)
